import React from 'react';
import Callout from '../img/callout-image.jpg';
import Callout2 from '../img/callout2.png';
import Callout3 from '../img/callout3.jpg';


const HowSection = ()=> {
    return(
        <section className="download text-center" id="download">
        <div className="container">
          <div className="row ">
            <h2 style={{ margin: "auto", fontWeight: "bold", fontSize: "42px" }} >Here's How</h2>
          </div>
          <div className="row">
            <div className="col-md-4" style={{ minHeight: "400px" }}>
              <div style={{ margin: "30px", minHeight: "340px" }}>
                <div>
                  <img src={Callout} alt="callout" className="img-fluid" />
                </div>
                <div>
                  <h4 style={{ padding: "5px",color:"#4a4a4a",fontSize:"24px" }}>Get Fit. Do Good. </h4>
                  <p style={{ padding: "0 30px 30px 30px", textAlign: "start" }}>
                    Walk/jog daily to remain fit, and raise money for charity while getting fit. Your workout are
                    sponsored by our proud corporate partners. Help someone in need, feel great all day :)
                  </p>
                </div>
              </div>

            </div>
            <div className="col-md-4" style={{ minHeight: "400px" }}>
              <div style={{ margin: "30px", minHeight: "340px" }}>
                <div>
                  <img src={Callout2} alt="callout" className="img-fluid" />
                </div>
                <div>
                  <h4 style={{ padding: "5px",color:"#4a4a4a",fontSize:"24px" }}>Trusted NGO Partners </h4>
                  <p style={{ padding: "0 30px 30px 30px", textAlign: "start" }}>
                  We handpick the NGOs, look at the Impact they are creating, and bring them onboard like a family.
                   All the money generated by your workout goes to the needy.
                  </p>
                </div>
              </div>
            </div>
            <div className="col-md-4" style={{ minHeight: "400px" }}>
              <div style={{ margin: "30px", minHeight: "340px" }}>
                <div>
                  <img src={Callout3} alt="callout" className="img-fluid" />
                </div>
                <div>
                  <h4 style={{ padding: "5px",color:"#4a4a4a",fontSize:"24px" }}>Thanks to  our sponsors </h4>
                  <p style={{ padding: "0 30px 30px 30px", textAlign: "start" }}>
                  We’re grateful to be sponsored by awesome brands like Hero Motocorp, Aarti Industries, Wockhardt, and Barclays! And we hope you will be too. We can’t do this without their support!
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    )
}

export default HowSection;