import React from 'react';
import Callout from '../img/callout-image.png';
import Callout2 from '../img/callout2.jpg';
import Callout3 from '../img/corporate-image.jpg';


const HowSection = ()=> {
    return(
        <section className="download text-center" id="download">
        <div className="container">
          <div className="row ">
            <h2 style={{ margin: "auto", fontWeight: "bold", fontSize: "42px",paddingBottom:"30px" }} >Here's How</h2>
          </div>
          <div className="row">
            <div className="col-sm-4" style={{ minHeight: "400px" }}>
              <div style={{ minHeight: "340px" }}>
                <div>
                  <img src={Callout} alt="callout" className="img-fluid"  />
                </div>
                <div className="how-paragraph">
                  <h4 style={{ color:"#4a4a4a",fontSize:"24px" }}>Get Fit. Do Good. </h4>
                  <p style={{  textAlign: "start" }}>
                  Walk, jog every day and raise money for charity while getting fit. Your workouts are sponsored by our proud corporate partners. And the funds raised are donated to non-profits working in various social sectors. 
                  Help the needy in a simple way. And you will surely feel great all day&nbsp;:)
                  </p>
                </div>
              </div>

            </div>
            <div className="col-sm-4" style={{ minHeight: "400px" }}>
              <div style={{ minHeight: "340px" }}>
                <div>
                  <img src={Callout2} alt="callout" className="img-fluid" />
                </div>
                <div  className="how-paragraph">
                  <h4 style={{ color:"#4a4a4a",fontSize:"24px" }}>Trusted NGO Partners </h4>
                  <p style={{  textAlign: "start" }}>
                  We handpick non-profits considering the on-ground impact they are creating and bring them onboard like a family. Think Foundation, Naam Foundation, American Red Cross, Army Wives Welfare Association are some of our non-profit partners. 
                  All the money generated by your workouts goes directly to the beneficiaries.
                  </p>
                </div>
              </div>
            </div>
            <div className="col-sm-4" style={{ minHeight: "400px" }}>
              <div style={{ minHeight: "340px" }}>
                <div>
                  <img src={Callout3} alt="callout" className="img-fluid" />
                </div>
                <div  className="how-paragraph">
                  <h4 style={{color:"#4a4a4a",fontSize:"24px" }}>Thanks to  our sponsors </h4>
                  <p style={{textAlign: "start" }}>
                  We are honoured and extremely grateful to have caring companies like Hero Motocorp, Aarti Industries, Wockhardt, Jubilant Lifesciences, Welspun and Barclays as our proud sponsors. 
                  And we hope you will be too. We can't do this without their support!
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    )
}

export default HowSection;